### ISSUE TITLE
bug: Inconsistent visualization of LangChain messages in nested observations

### ISSUE THREAD

**Issue by Stadly** [langfuse/langfuse#1213]
### Describe the bug

When looking at the `RunnableSequence`, the output is not very nice:
![image](https://github.com/langfuse/langfuse/assets/7263579/034d0b5e-ecfe-4d78-8e9e-118574dbd5cf)

When looking at `ChatOpenAI`, the output looks good:
![image](https://github.com/langfuse/langfuse/assets/7263579/11ed48ab-5a7a-43ce-b318-acac51eb1f03)

As `ChatOpenAI` is the last observation nested in `RunnableSequence`, I would have expected the outputs to equal.

### To reproduce

```js
const llm = new ChatOpenAI({
  azureOpenAIApiKey: AZURE_OPENAI_API_KEY,
  azureOpenAIApiInstanceName: AZURE_OPENAI_API_INSTANCE_NAME,
  azureOpenAIApiDeploymentName: AZURE_OPENAI_API_DEPLOYMENT_NAME,
  azureOpenAIApiVersion: AZURE_OPENAI_API_VERSION,
  modelName: "gpt-4",
  verbose: true,
})

const handler = new CallbackHandler({
  secretKey: LANGFUSE_SECRET_KEY,
  publicKey: LANGFUSE_PUBLIC_KEY,
  baseUrl: LANGFUSE_BASE_URL,
});

const tpl = PromptTemplate.fromTemplate("Tell me a joke about {topic}.");
const chain = RunnableSequence.from([
  tpl,
  llm,
]);
await chain.invoke({ topic: "bears" }, { callbacks: [handler] });
```

### Additional information

I'm using the JavaScript SDK, version 3.1.0

**Comment by marcklingen** [comment]
This is generally working as intended for now:
- All Langchain Inputs/outputs are serialized to trace the full context of what's going on in agents/chains
- For LLM calls specifically, we parse the Chatmessage format in order to allow for downstream fine-tuning and evaluation.

I understand that in this special case the trace could be nicer as your higher-level spans do not include any additional context in addition to the chat message.
