### ISSUE TITLE
[LFC-171] Scroll to observations when opening an observation

### ISSUE THREAD

**Issue by marcklingen** [langfuse/langfuse#178]
**Current behavior**

When clicking on specific Generations or Spans in the detail view of traces, we adjust the link. The Link has the following structure: `https://cloud.langfuse.com/project/<project-id>/traces/<trace-id>?observation=<observation-id>`

The <observation-id> changes according to the navigation in the Trace.

When opening this Link, the Trace Detail view renders with the trace navigation scrolled all the way up. In the following picture, we cannot see the currently opened Generation, which should have a grey background.

**Desired behavior**

Traces can become very long and finding the specific Generation or Span can be tedious. Hence it would be great to scroll to the right element on page load as in the following picture

<sub>From [SyncLinear.com](https://synclinear.com) | [LFC-171](https://linear.app/langfuse/issue/LFC-171/scroll-to-observations-when-opening-an-observation)</sub>

**Comment by DIWAKARKASHYAP** [comment]
I don't get this issue 😕, what you actually want ?

**Comment by maxdeichmann** [comment]
> I don't get this issue 😕, what you actually want ?

The problem is: When you have very long traces with say 20 generations, navigating becomes tedious. When you click on an element on the trace view, 'prompt-empedding' in this case, it shows the details of that step.
<img width="1457" alt="image" src="https://github.com/langfuse/langfuse/assets/17686849/912a3540-aafe-497a-81c0-7587e8d62349">

If you now scroll on the right, and click on another element, it shows these details again. If you now navigate back, it does not scroll automatically to the element which was selected before. Hence, you need to scroll again to find it.

**Comment by gokuljs** [comment]
is there a easier way to populate data into this in local ?
