### ISSUE TITLE
bug: Not able to add LLM API Keys on Langfuse UI

### ISSUE THREAD

**Issue by ashutoshsaboo** [langfuse/langfuse#2629]
### Describe the bug

Self hosted installation. Go to playground tab -> add new llm api key -> enter normal keys for openai which work as normal with the openai client. And it shows "Invalid key length" error Path: llmApiKey.create. 

See screenshot below: 
<img width="353" alt="image" src="https://github.com/user-attachments/assets/a8316694-0610-4da0-b5f7-2c9004af5e7e">

cc: @marcklingen 

### To reproduce

All details mentioned above already. 

### SDK and container versions

Using langfuse/langfuse:latest docker image.
Client sdk version is - langfuse==2.39.1

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
Can you share what you did to resolve this issue?

**Comment by marcklingen** [comment]
> [@ashutoshsaboo](https://github.com/ashutoshsaboo) what did you do to solve this?

Can you create a new issue for this?

**Comment by klampzlamps** [comment]
I just encountered this issue and it wasn't a Langfuse problem, it was an issue with my ENCRYPTION_KEY env var. 

[Internally Langfuse encrypts the secret keys](https://github.com/langfuse/langfuse/blob/7598c95fc3c962e387d398f88e27329466d95780/web/src/features/llm-api-key/server/router.ts#L146C24-L146C31) with [AES-256-GCM which expects a 256-bit, 64 character string in hex format](https://github.com/langfuse/langfuse/blob/7598c95fc3c962e387d398f88e27329466d95780/packages/shared/src/encryption/encryption.ts#L23). The problem was my key wasn't in hex format which leads to the "INVALID_KEY_LEN" error.
