### ISSUE TITLE
bug: name-based virtual hosting doesn't seem to be supported?

### ISSUE THREAD

**Issue by jabbasj** [langfuse/langfuse#2811]
### Describe the bug

When deploying the application under a hostname with a specific sub-path like https://hostdomain.com/langfuse

Front-end gets stuck at "Loading.." and in the backend requests appear as 404

![image](https://github.com/user-attachments/assets/87d40583-4223-478e-9521-0569a70268ba)
![image](https://github.com/user-attachments/assets/3a3e631b-af24-474d-9c7d-50dbc39a995f)

I deployed the app in CloudRun using a loadbalancer and defined the path as /langfuse

### To reproduce

Deploy the app in CloudRun using a loadbalancer and defined the path as /langfuse and /langfuse/* while having another app under /* with the same hostname

### Are you interested to contribute a fix for this bug?

No

**Comment by henrique-tostes-a3** [comment]
I'm with the same problem, but in aws deploying with EKS(k8s)

**Comment by marcklingen** [comment]
thanks for reporting, tracking this here: https://github.com/orgs/langfuse/discussions/2400

**Comment by a-imran99** [comment]
@jabbasj  @henrique-tostes-a3 , Is this achievable, facing same problem with k8s while trying to host under subpath.

When building the source code with basePath all the assets are nested inside the basepath
Ideally should be found under {domain}/basePath
But found under {domain}/basePath/basePath

My Build command:
docker build -t langfuse/langfuse:3.0.11 --build-arg NEXT_PUBLIC_BASE_PATH=/{basePath} -f ./web/Dockerfile .

Serving the application using ingress

Suggest!

**Comment by marcklingen** [comment]
Did you check out this page? https://langfuse.com/self-hosting/custom-base-path

**Comment by a-imran99** [comment]
@marcklingen Followed the steps in above document but this works only when the path in ingress in pointed to root which is /
Works with below configs:
- path: /(.*)
pathType: Prefix
backend:
  service:
	name: langfuse-service
	port:
	  number: 80

But doesnot work with below config:
- path: /langfuse(/|$)(.*)
pathType: Prefix
backend:
  service:
	name: langfuse-service
	port:
	  number: 80

**Comment by marcklingen** [comment]
So this works when ingress maps the basepath to root? I.e. all assets then work correctly?

**Comment by a-imran99** [comment]
@marcklingen yes works perfectly

**Comment by marcklingen** [comment]
I'm not an expert on this, generally custom base path deployments have not been an issue in the past. I'd appreciate it if you share any findings you make on this in this thread.

**Comment by a-imran99** [comment]
@marcklingen 

I have a subdomain https://trace.mymaindomain.com

I have two application, langfuse and app2

In ingress, I have mapped app2 service to the root directory of my domain meaning after containerazing the app2 and running app2 as a service, I mapped this service to root of this url https://trace.mymaindomain.com

Second I have langfuse which i need to host on subpath of the above url (https://trace.mymaindomain.com/my_sub_path) 

This is the requirement. But the challenges I am facing is I cannot host it in the required subpath

I built the langfuse with subpath argument with the below docker command.
docker build -t langfuse/langfuse:3.0.11 --build-arg NEXT_PUBLIC_BASE_PATH=/{my_sub_path} -f ./web/Dockerfile .

After building and dockerizing, I tried to map this to my subpath of the root domain that is https://trace.mymaindomain.com/my_sub_path . But all the static assets are under https://trace.mymaindomain.com/my_sub_path/my_sub_path

Seems like static assets are nested. It seems the image running as service already has all the static assets under a subpath and when this is pointed to subpath in ingress it gets nested.

But when I map langfuse image to the root directory i.e https://trace.mymaindomain.com/ 
This works because there is not subpath in ingress and every assets are under my subpath when building the langfuse image
when I try to access the root site which is langfuse and not app2 everything works correct.

-----------------------------------------------------------------------------------------------------------------------------------------------
I am trying to build langfuse image without subpath and trying to serve under https://trace.mymaindomain.com/my_sub_path from ingress. I am using nginx to serve the application.

**Comment by marcklingen** [comment]
Thanks for sharing! You might find it interesting to explore the Next.js basePath documentation, as Langfuse utilizes this feature to support custom base path deployments: https://nextjs.org/docs/pages/api-reference/config/next-config-js/basePath
