### ISSUE TITLE
bug: importing Langfuse results in error

### ISSUE THREAD

**Issue by chernomord** [langfuse/langfuse#377]
### Describe the bug

`from langfuse import Langfuse` causes the following error:

> ImportError: cannot import name 'ENCODERS_BY_TYPE' from 'pydantic.json'

### To reproduce

run `pip3 install langfuse`
type `from langfuse import Langfuse` in Jypiter notebook.
For some reason, it works fine in python outside of Jypiter

Also, try to lock pydantic below v2.   Langfuse doesn't control it (on purpose?) yet Pydantic v2 won't work with Langfuse for different reasons.

### Additional information

environment: pyton 3.8, conda.

**Comment by maxdeichmann** [comment]
@chernomord thanks for reporting this. Did you try to execute our Notebook here? https://colab.research.google.com/github/langfuse/langfuse-docs/blob/main/src/ipynb/langfuse_docs_sdk_python.ipynb
If i try it, everything works just fine.

Regarding Pydantic, we want to get rid of the dependency or comply with 2.x and 1.x. See the issue here: https://github.com/langfuse/langfuse/issues/228

**Comment by marcklingen** [comment]
Closing this issue for now as the strict dependency on Pydantic v1 is resolved and the Langfuse Python SDK now also is compatible with Pydantic v2
