### ISSUE TITLE
bug: VertexAI in new experiment (prompts) doesn't work

### ISSUE THREAD

**Issue by kamonspecial** [langfuse/langfuse#4632]
### Describe the bug

When I pick the vertex AI in the new experiment from prompts, No trace run and can't see any result in Dataset-run. Hence, No score is added.The API key is valid, I ensure that the playground does work.
![image](https://github.com/user-attachments/assets/2815be98-e3ac-491e-82d2-d3fc1b71ec47)
![image](https://github.com/user-attachments/assets/ef7da180-2712-446f-8ca2-6d5b1bbcef83)
![image](https://github.com/user-attachments/assets/ddffed9c-f1b4-4de2-b2aa-353aa295cd26)

### To reproduce

In SaaS Langfuse (v3.0.0-rc.4), pick VertexAI in New experiment from prompt with a simple dataset for testing.

### Are you interested to contribute a fix for this bug?

No

**Comment by marliessophie** [comment]
Hey @kamonspecial, thanks for reporting this. To achieve a situation where your experiments run smoothly, and in case they do not run as expected (e.g. due to quota limits), you receive a digestable error message. 

- To this end, we fixed the VertexAI for `text` prompts: https://github.com/langfuse/langfuse/commit/b63aeeeae7a3e53ef1f23d21c8bd610c4a89c8d2
- We're added support for error logs in experiment runs, should be live soon https://github.com/langfuse/langfuse/pull/4698
