### ISSUE TITLE
feat: improve design of scrollbar

### ISSUE THREAD

**Issue by DIWAKARKASHYAP** [langfuse/langfuse#503]
### Describe the feature you'd like to request

A large scrollbar appears in Chrome but not in Firefox
![image](https://github.com/langfuse/langfuse/assets/94478026/4e19f534-a92d-453e-8d5b-8f78457a5942)

### Describe the solution you'd like to see

Make the scrollbar smaller using CSS

### Additional information

Please comment with the browser name if your browser has the same scrollbar

### Contribute

- [X] Yes, I can implement this and raise a PR

**Comment by gokuljs** [comment]
@marcklingen, for this particular issue, I recommend installing a scroll bar component for the file and wrapping the sidebar in Radix. You can find more information about Radix here: [Radix Scroll Area](https://www.radix-ui.com/primitives/docs/components/scroll-area).

Alternatively, if you have your own custom scroll bar design, please share the Figma link with me, and I'll be happy to assist in resolving the issue.

**Comment by gokuljs** [comment]
You can take a look at a few more examples [radix-themes](https://www.radix-ui.com/themes/docs/components/scroll-area)

**Comment by gokuljs** [comment]
@marcklingen I have implemented a fix for the scrollbar issue mentioned above and have included a video demonstrating its functionality. Please review and merge the pull request.

**Comment by gokuljs** [comment]
@marcklingen, so I saw the previous PR where you have updated the scrollbar design, but there is one issue: when it becomes scrollable, even the Langfuse symbol scrolls to the top. This isn't considered a good UX decision because it can disorient users, make navigation more difficult, diminish brand presence, and deviate from standard web conventions that users are accustomed to. The logo typically serves as a home anchor and should remain easily accessible at all times to ensure a consistent and user-friendly experience.

**Comment by marcklingen** [comment]
Thanks again for making this change @gokuljs. Closing this issue
